### ISSUE TITLE
error/ it violates the following Content Security Policy directive

### ISSUE THREAD

**Issue by LuisTorres1992** [Guillerbr/rbac-node-acl-mongo#15]
Hi, I have a problem trying to run, I have installed the dependencies, I modified the Mongodb credentials, and I get that error, I am a rookie, thank you very much in advance

![image](https://user-images.githubusercontent.com/56885770/73618306-bccb5380-45f4-11ea-9cb4-c5fef701ae97.png)

**Comment by LuisTorres1992** [comment]
![image](https://user-images.githubusercontent.com/56885770/73618365-4713b780-45f5-11ea-8376-b3ced1be0b99.png)

**Comment by Guillerbr** [comment]
Now you need to call a functional route, the 5500 / is not one.
Test the api at 5500 / ping and then register a new user at 5500 / signup.

Reread the Readme.md instruction file
